# Pandas DataFrame Access Methods

This notebook demonstrates various ways to access data in a Pandas DataFrame, including columns, rows, multiple rows/columns, filtering, and accessing specific cells using `loc`, `iloc`, `at`, and `iat`.

## Import Required Libraries

In [1]:
import pandas as pd

## Create a Sample DataFrame

In [2]:
data = {
    'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'],
    'Age': [25, 30, 22, 35, 28],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Salary': [50000, 55000, 40000, 70000, 48000]
}
df = pd.DataFrame(data)
df

      Name  Age  Gender  Salary
0     John   25    Male   50000
1    Alice   30  Female   55000
2      Bob   22    Male   40000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

## Access the Entire DataFrame

Simply refer to the DataFrame variable to display all data.

In [ ]:
df

## Access a Column

Access a column using bracket notation.

In [4]:
df['Name']

0       John
1      Alice
2        Bob
3        Eve
4    Charlie
Name: Name, dtype: object

## Access a Row by Index (iloc)

Use `iloc` for positional indexing.

In [18]:
print(df.iloc[4])  # Second row
df.iloc[2:4,1:3]  # Second row, third column

Name      Charlie
Age            28
Gender       Male
Salary      48000
Name: 4, dtype: object

   Age  Gender
2   22    Male
3   35  Female

## Access Multiple Rows or Columns

Select multiple rows or columns by passing lists.

In [11]:
df.loc[0:1,["Name","Salary"]]  # First three rows, Name and Age columns

    Name  Salary
0   John   50000
1  Alice   55000

## Access Rows Based on Condition

Filter rows where Age > 25.

In [25]:
df[df['Age'] > 25]
df[df["Gender"] =="Male"]  # Filter rows where Salary is greater than 50000  ]

      Name  Age Gender  Salary
0     John   25   Male   50000
2      Bob   22   Male   40000
4  Charlie   28   Male   48000

## Access a Specific Cell with at and iat

Use `at` for label-based and `iat` for integer position-based access.

In [26]:
df.at[2, 'Salary']  # Salary of row with index 2

np.int64(40000)

In [ ]:
df.iat[2, 3]  # Third row, fourth column (Salary)