# Indexing and Selecting Data with Pandas

This notebook demonstrates various ways to index and select data in Pandas DataFrames, including column selection, row selection, slicing, boolean indexing, and advanced indexing methods.

## Import Required Libraries

In [1]:
import pandas as pd

## Read data from csv

In [18]:
df=pd.read_csv('../data/algo_trading_data.csv',index_col='Date')
df

            Open  High  Low  Close  Volume
Date
2023-01-01   100   105   95    102    1000
2023-01-02   101   106   96    103    1010
2023-01-03   102   107   97    104    1020
2023-01-04   103   108   98    105    1030
2023-01-05   104   109   99    106    1040
2023-01-06   105   110  100    107    1050
2023-01-07   106   111  101    108    1060
2023-01-08   107   112  102    109    1070
2023-01-09   108   113  103    110    1080
2023-01-10   109   114  104    111    1090

## Selecting Columns
You can select a single column or multiple columns using the indexing operator [].

In [20]:
# df.head(5)
display(df.head(5)[['Open','High','Low','Close']])

            Open  High  Low  Close
Date
2023-01-01   100   105   95    102
2023-01-02   101   106   96    103
2023-01-03   102   107   97    104
2023-01-04   103   108   98    105
2023-01-05   104   109   99    106

In [19]:
# Select multiple columns
df[df["Volume"]>1050]

            Open  High  Low  Close  Volume
Date
2023-01-07   106   111  101    108    1060
2023-01-08   107   112  102    109    1070
2023-01-09   108   113  103    110    1080
2023-01-10   109   114  104    111    1090

## Selecting Rows by Index
Use `iloc` for integer-location based indexing and `loc` for label-based indexing.

In [ ]:
# Select the first row
df.iloc[0]

In [ ]:
# Select rows by label
df.loc[0:2]  # Rows with index 0, 1, 2

## Slicing Rows and Columns
You can slice both rows and columns using `loc` and `iloc`.

In [ ]:
# Select first three rows and 'Name', 'Age' columns
df.loc[0:2, ['Name', 'Age']]

## Boolean Indexing
Filter rows based on a condition.

In [ ]:
# Select rows where Age > 25
df[df['Age'] > 25]

## Accessing a Single Value
Use `at` for label-based and `iat` for integer position-based access.

In [ ]:
# Access the Salary of the row with index 2
df.at[2, 'Salary']

In [ ]:
# Access the value at row 2, column 3 (Salary)
df.iat[2, 3]

# Pandas DataFrame: Merging, Joining, and Concatenating

This notebook demonstrates how to combine DataFrames in pandas using merging, joining, and concatenating methods.

## Import Required Libraries

In [ ]:
import pandas as pd

## Create Sample DataFrames

In [ ]:
data1 = {
    'ID': [1, 2, 3, 4],
    'Name': ['John', 'Alice', 'Bob', 'Eve']
}
data2 = {
    'ID': [3, 4, 5, 6],
    'Salary': [40000, 50000, 60000, 70000]
}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df1, df2

## Merging DataFrames
Use `pd.merge()` to combine DataFrames based on a common column.

In [ ]:
# Inner join (only matching IDs)
merged_inner = pd.merge(df1, df2, on='ID', how='inner')
merged_inner

In [ ]:
# Outer join (all IDs, fill missing with NaN)
merged_outer = pd.merge(df1, df2, on='ID', how='outer')
merged_outer

## Joining DataFrames
Use `DataFrame.join()` to join on the index.

In [ ]:
df3 = df1.set_index('ID')
df4 = df2.set_index('ID')
joined = df3.join(df4, how='inner')
joined

## Concatenating DataFrames
Use `pd.concat()` to stack DataFrames vertically or horizontally.

In [ ]:
# Concatenate vertically (default axis=0)
concat_vertical = pd.concat([df1, df2], ignore_index=True)
concat_vertical

In [ ]:
# Concatenate horizontally (axis=1)
concat_horizontal = pd.concat([df1, df2], axis=1)
concat_horizontal