# Handling Missing Data

### Checking for missing values using isnull()

In [29]:
import pandas as pd
import numpy as np

# Create a demo dataset for algorithmic trading
data = {
    'Date': pd.date_range(start='2023-01-01', periods=10, freq='D'),
    'Open': [100, 102, np.nan, 105, 107, np.nan, 110, 112, 113, np.nan],
    'High': [101, 103, 104, 106, 108, 109, 111, 113, 114, 115],
    'Low': [99, 101, 102, 104, np.nan, 108, 109, 111, np.nan, 114],
    'Close': [100.5, 102.5, 103.5, np.nan, 107.5, 108.5, 110.5, 112.5, 113.5, 114.5],
    'Volume': [1000, 1100, 1200, 1300, 1400, np.nan, 1600, 1700, 1800, 1900]
}

# Create a DataFrame
df=pd.DataFrame(data)
mv=df.isnull()
mv=df.notnull()
df

        Date   Open  High    Low  Close  Volume
0 2023-01-01  100.0   101   99.0  100.5  1000.0
1 2023-01-02  102.0   103  101.0  102.5  1100.0
2 2023-01-03    NaN   104  102.0  103.5  1200.0
3 2023-01-04  105.0   106  104.0    NaN  1300.0
4 2023-01-05  107.0   108    NaN  107.5  1400.0
5 2023-01-06    NaN   109  108.0  108.5     NaN
6 2023-01-07  110.0   111  109.0  110.5  1600.0
7 2023-01-08  112.0   113  111.0  112.5  1700.0
8 2023-01-09  113.0   114    NaN  113.5  1800.0
9 2023-01-10    NaN   115  114.0  114.5  1900.0

### 2.filtering data based on missing values

In [ ]:
# Filter rows where 'Open' column has missing values
missing_open = df[df['Volume'].notnull()]
print(missing_open)
print(df)

## Filling Missing Values in Pandas Using fillna(), replace() and interpolate()

In [27]:
# using filna()

fill_with_zero=df.fillna(0)
fill_with_zero
# df.fillna(method='bfill')

        Date   Open  High    Low  Close  Volume
0 2023-01-01  100.0   101   99.0  100.5  1000.0
1 2023-01-02  102.0   103  101.0  102.5  1100.0
2 2023-01-03      -   104  102.0  103.5  1200.0
3 2023-01-04  105.0   106  104.0      -  1300.0
4 2023-01-05  107.0   108      -  107.5  1400.0
5 2023-01-06      -   109  108.0  108.5       -
6 2023-01-07  110.0   111  109.0  110.5  1600.0
7 2023-01-08  112.0   113  111.0  112.5  1700.0
8 2023-01-09  113.0   114      -  113.5  1800.0
9 2023-01-10      -   115  114.0  114.5  1900.0

### Using replace()

In [ ]:
df.replace(to_replace=np.nan, value=-99)
# df

## Dropping Missing Values in Pandas Using dropna()

In [43]:
dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, np.nan]}
df = pd.DataFrame(dict)

# Drop rows with at least one missing value
df.dropna() # Drop rows with at least one missing value
df.dropna(how='all') # Drop rows with all missing values
df.dropna(thresh=2) # Drop rows with at least 2 non-NA values
df.dropna(axis=1)

   Third Score
0           52
1           40
2           80
3           98